export const specialties = [
    "Acupuncturist",
    "Aesthetic Doctor",
    "Algologist",
    "Allergologist",
    "Anesthesiologist",
    "Angiologist",
    "Audiologist",
    "Cardiologist",
    "Chiropodist",
    "Chiropractor",
    "Clinic Nutritionist",
    "Clinical Analyst",
    "Complementary Therapis",
    "Cosmetic Surgeon",
    "Critical Medicine and Intensive Therapy Specialist",
    "Dentist / Odontologist",
    "Dermatologist",
    "Diabetologist",
    "Educational Psychologist",
    "Endocrinologist",
    "Endoscopist",
    "Family Doctor",
    "Gastroenterlogist",
    "General Doctor",
    "General Surgeon",
    "Geneticist",
    "Geriatrician",
    "Gynecologist",
    "Hand Surgeon",
    "Hematologist",
    "Homoepathist",
    "Immunologist",
    "Integrated Medicine Specialist",
    "Internist",
    "Maxillofacial Surgeon",
    "Medical and surgical retina specialist",
    "Medical Oncologist",
    "Naturist",
    "Neonatology",
    "Nephrologist",
    "Neurologist",
    "Neurophysiologist",
    "Neurosurgeon",
    "Nuclear Medicine Specialist",
    "Nurse",
    "Nutritionist",
    "Obesity and Thinness Specialist",
    "Occupational Medicine Specialist",
    "Occupational Therapist",
    "Oncological Gynecologist",
    "Ophthalmologist",
    "Optometrist",
    "Orthopedist",
    "Otorhinolaryngologist",
    "Pathologist",
    "Pediatric Cardiologist",
    "Pediatric Dermatologist",
    "Pediatric Endocrinologist",
    "Pediatric Gastroenterlogist",
    "Pediatric Hematologist",
    "Pediatric Nephrologist",
    "Pediatric Neurologist",
    "Pediatric Oncologist",
    "Pediatric Ophthalmologist",
    "Pediatric Orthopedist",
    "Pediatric Psychiatrist",
    "Pediatric Pulmonologist",
    "Pediatric Rheumatologist",
    "Pediatrician",
    "Physiotherapist",
    "Plastic Surgeon",
    "Podiatrist",
    "Preventive Medicine Specialist",
    "Proctologist",
    "Psychiatrist",
    "Psychoanalyst",
    "Psychologist",
    "Pulmonologist",
    "Radiologist",
    "Radiotherapist",
    "Rehabilitation and Physical Medicine Specialist",
    "Rheumatologist",
    "Sexologist",
    "Speech Therapist",
    "Sports Medicine Specialist",
    "Traumatologist",
    "Urgenciologist",
    "Urologist"
]